
language: java
language: python

env:
  - NODE_VERSION="12.13.1"

#services:
#  - docker

jdk:
  - openjdk11


addons:
  sonarcloud:
    organization: "edin0"
    token:
      secure: "pDexrsiQGeaLoWbG0fl/qnTGg7FpnBO/qSlxdi7C8Ynsor4JesPruNo05mT6tOfgp6DtDzQegcs72hqMQd1LIcKdhKu9IwdjjRoW2lV8W/pRnV9SKTHK7bBMdV1dCfMvgdUbIcMAkmFUS2FUGRjdRfRPmpTZ5gfxayOfu0+iApBCNXfQPCOopS9yBrM146pdxyhy+uEf4npPMH00xqK2SP2Qa7bqCvHXpRzrC43z4PUkBx2W3acm9lKfJGCf6rTzz2wLBNHLW9GkXd0i2QdNtu7iUtN14Iqy29ODdo1WDAobUyNDnP8r9bZQ4uPCtkNFEyEa+dIicYmK7Fy0sqBLg4z0p4ZUcIp8dq4vfHBZPocDteKoL0V04DXyqHIqWLsu+OW47cfQo4XxyOLCAUrq2LfmrKGKgIG8maw+WGSJwX2vmXimXjJwtikeYLJkkQiLqqzfJAFuzoTuwpgLJQaYVzTph9+yJd0JsFoJcrsulY9gmer1oj9/rShkeBf6nrtVkDXSiU5jNh2Oy1pTmdTAoW1Jejw2Rs0E3zs7v5yoA0rgHwAGCeIHUoIewccgofrChtvPfRA8AsZKldUxVbe0/kswOcQE5LVYW8klpztDAjR8q3xv9UYw3HVcIqPJUJkWENGlEj/XbYA8ByUnpCqZ9BFTxsU8ceCkeWpUJqQw1Zg="

script:
  - sonar-scanner
  - ./mvnw clean install




jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      #- docker build -t unige/web-ui .
      #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      #- docker tag unige/web-ui edin0/web-ui:latest      
      #- docker push edin0/web-ui:latest

    - stage: Test
      script: ./mvnw clean test


notification:
  email: edin.sljmn@gmail.com
