
language: java
jdk:
  - openjdk11


addons:
  sonarcloud:
    organization: "edin0"
    token:
      secure: "bSB5x6LbzLMwraJ6zP20T27XO/VaFrrX9gGEZ1sYYqyedtyyll++FwBIx6ZW22PF4UqOVRF9Kxo/u37uqCCDn5pJjpltsXWV/bF9BWBiPpg3H29RKMF5T+k9hh1qpSoNdNmEuFfSxTxWIf/LV3tuigOsj/7VWncldnRYoXDglgNf7JEolCP3NVCojtRrCSgHWHCVWt1ILUKprv506d5hgBsL0foGbbU+ZkmvjIlgtpc5etsXkqXwcRnkwBU7c4C6DxSEqHeF57pgdObA1APTz31gx7ZrQMKyzgRBhrB+GoujmSo90lJ3iGGLdSAiMwGiOcVnaBAiaUb4ARd02HAQrkTuMxf7dalUoYXuLQWJI3oVaVknsYTNyOhRvpay488buaTL4FL21iNA0cohbrFHnu4flEGB4HT4FuMTAIrkY5Ljp0nwAwSlsBk/5rbWyQUnm6zr1YPhY1nX7RCjG4kJvrJZSG6b7Ed0XpQJ00RAaog0EKkzGTo9M7rhOXQzkKPrPeVILHKDQ4czx96j8Kxw4eqVxEvM5yJXXYIvWi9MBe9cZ4/z6rLnaYOH3KM+dEMaLCMEBMpChfFzfOjPJhNEO/kl7Eisvy7oJ+Ih47BM8JSWbD6jSPB1dl+jELQD27gKjsCKMmOXrzSjfpLiGkppZtdr5yWMNmj+bume/VKPnF0="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - sonar-scanner
  - ./mvnw clean install




jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

notification:
  email: edin.sljmn@gmail.com
